/* Celebrities page data.
   HOW TO ADD A STAR: copy one line, paste it before the closing ];, change the words, keep the commas and quotes.
   n = name, g = Screen / Music / Style, p = perfume, h = perfume house,
   w = where they said it (their own words only: interview, their own post, an event answer),
   s = link to the page that reports it.
   sl and i (optional) = the perfume's catalogue name and picture number, only when we stock that exact perfume. Without them the card shows initials.
   Only add a star if they said it themselves. Nothing guessed, nothing "reported". */
window.STARS = [
{n:"Victoria Beckham",g:"Style",p:"Room Service",h:"Vilhelm Parfumerie",w:"Her own Instagram",s:"https://whowhatwear.com/celebrity-favourite-perfumes"},
{n:"Ashley Graham",g:"Style",p:"Chloé Eau de Parfum",h:"Chloé",sl:"chloe-chloe-women",i:"216468397",w:"Interview with E! Online",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Gemma Arterton",g:"Screen",p:"Colonia Essenza",h:"Acqua di Parma",w:"Harper's Bazaar interview",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Kate Bosworth",g:"Screen",p:"Gypsy Water",h:"Byredo",sl:"byredo-gypsy-water-byredo-unisex",i:"216431900",w:"Into the Gloss, 2014",s:"https://whowhatwear.com/celebrity-favourite-perfumes"},
{n:"Rosie Huntington-Whiteley",g:"Style",p:"Gypsy Water",h:"Byredo",sl:"byredo-gypsy-water-byredo-unisex",i:"216431900",w:"Her own YouTube channel",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Margot Robbie",g:"Screen",p:"Deep Euphoria",h:"Calvin Klein",w:"Marie Claire interview",s:"https://whowhatwear.com/celebrity-favourite-perfumes"},
{n:"Paul Mescal",g:"Screen",p:"Another 13",h:"Le Labo",w:"GQ video",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Maya Jama",g:"Style",p:"Hypnotic Poison",h:"Dior",sl:"christian-dior-hypnotic-poison-women",i:"216263729",w:"Marie Claire UK, 2019",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Chrissy Teigen",g:"Style",p:"Hypnotic Poison",h:"Dior",sl:"christian-dior-hypnotic-poison-women",i:"216263729",w:"Interview with E! Online",s:"https://whowhatwear.com/celebrity-favourite-perfumes"},
{n:"Reese Witherspoon",g:"Screen",p:"Amber Musk",h:"Aerin",w:"Harper's Bazaar, 2016",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Jodie Comer",g:"Screen",p:"Santal 33",h:"Le Labo",sl:"le-labo-le-labo-santal-33-women",i:"216399842",w:"Harper's Bazaar \"Inside My Beauty Bag\"",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Alexa Chung",g:"Style",p:"Santal 33",h:"Le Labo",sl:"le-labo-le-labo-santal-33-women",i:"216399842",w:"Elle, 2012",s:"https://whowhatwear.com/celebrity-favourite-perfumes"},
{n:"Elizabeth Olsen",g:"Screen",p:"Philosykos solid perfume",h:"Diptyque",w:"Harper's Bazaar",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Eva Longoria",g:"Screen",p:"Portofino '97",h:"Victoria Beckham Beauty",w:"Harper's Bazaar",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Naomi Campbell",g:"Style",p:"Diorissimo",h:"Dior",sl:"christian-dior-diorissimo-women",i:"216347479",w:"2018 Fragrance Foundation Awards",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Meghan Markle",g:"Style",p:"Wild Bluebell",h:"Jo Malone London",sl:"jo-malone-jo-malone-wild-bluebell-women",i:"216431911",w:"Her old blog (not current)",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Hailey Bieber",g:"Style",p:"Fleur Narcotique",h:"Ex Nihilo",w:"Bustle, 2021",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Lizzo",g:"Music",p:"Molecule 01",h:"Escentric Molecules",sl:"escentric-molecules-escentric-molecule-01-unisex",i:"216326332",w:"New York Times, 2019",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Olivia Rodrigo",g:"Music",p:"Baccarat Rouge 540",h:"Maison Francis Kurkdjian",sl:"maison-francis-kurkdjian-maison-francis-kurkdjian-baccarat-rouge-540-unisex",i:"216423225",w:"British Vogue, 2021",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Doja Cat",g:"Music",p:"Black Saffron",h:"Byredo",sl:"byredo-black-saffron-byredo-unisex",i:"216508410",w:"Harper's Bazaar, 2021",s:"https://www.marieclaire.co.uk/beauty/fragrance/celebrity-perfumes"},
{n:"Taylor Swift",g:"Music",p:"Santal Blush",h:"Tom Ford",sl:"tom-ford-tom-ford-santal-blush-women",i:"216447821",w:"Her answer at the MTV VMAs",s:"https://www.harpersbazaar.in/beauty/story/these-are-the-fragrances-loved-by-the-stars-from-sienna-miller-to-beyonce-1105123-2024-10-11"},
{n:"Rita Ora",g:"Music",p:"Atelier des Fleurs Magnolia Alba",h:"Chloé",sl:"chloe-chloe-atelier-des-fleurs-magnolia-alba-women",i:"216364769",w:"Harper's Bazaar video",s:"https://www.harpersbazaar.com.sg/beauty/perfumes-a-listers-actually-wear"},
{n:"Awkwafina",g:"Screen",p:"Santal 33",h:"Le Labo",sl:"le-labo-le-labo-santal-33-women",i:"216399842",w:"Into The Gloss, 2017",s:"https://intothegloss.com/2017/04/awkwafina-beauty/"},
{n:"Cynthia Erivo",g:"Screen",p:"Lys 41 layered with Witchy Woo",h:"Le Labo and Vyrao",w:"USA Today interview, 2025",s:"https://www.aol.com/articles/cynthia-erivo-had-witchy-way-160424558.html"},
{n:"Julianne Moore",g:"Screen",p:"Original Musk",h:"Kiehl's",sl:"kiehl-s-kiehl-s-original-musk-women",i:"216142250",w:"Marie Claire interview, 2023",s:"https://www.marieclaire.com/beauty/julianne-moore-beauty-health-wellness-secrets/"},
{n:"Priyanka Chopra",g:"Screen",p:"La Panthère",h:"Cartier",sl:"cartier-cartier-la-panthere-women",i:"216252232",w:"Who What Wear interview, 2023",s:"https://whowhatwear.com/priyanka-chopra-beauty-secrets"},
{n:"Sienna Miller",g:"Screen",p:"Thé Noir 29",h:"Le Labo",sl:"le-labo-le-labo-the-noir-29-women",i:"216494371",w:"Harper's Bazaar \"Inside My Beauty Bag\", 2025",s:"https://www.womanandhome.com/beauty/sienna-miller-le-labo-perfume/"},
{n:"Helen Mirren",g:"Screen",p:"Blackberry & Bay Cologne",h:"Jo Malone London",sl:"jo-malone-jo-malone-blackberry-bay-women",i:"216286874",w:"Harper's Bazaar beauty bag video, 2025",s:"https://womanandhome.com/beauty/beauty-news/helen-mirren-favorite-perfume"},
{n:"Gillian Anderson",g:"Screen",p:"Orphéon solid perfume",h:"Diptyque",w:"Harper's Bazaar beauty bag video, 2025",s:"https://womanandhome.com/beauty/gillian-anderson-diptyque-perfume"},
{n:"Kate Winslet",g:"Screen",p:"L'Eau d'Issey",h:"Issey Miyake",sl:"issey-miyake-l-eau-d-issey-women",i:"216311769",w:"Vogue UK interview, 2021",s:"https://www.womanandhome.com/beauty/kate-winslet-perfume/"},
{n:"Emma Stone",g:"Screen",p:"A La Nuit",h:"Serge Lutens",w:"ET Online, 2013 (she had just bought it)",s:"https://www.etonline.com/node/36913"},
{n:"Kristen Bell",g:"Screen",p:"White Musk",h:"Jovan",sl:"jovan-jovan-white-musk-women",i:"216116303",w:"Marie Claire, 2010 (worn since she was 16)",s:"https://marieclaire.com/celebrity/a4259/kristen-bell-interview"},
{n:"Lady Gaga",g:"Music",p:"Womanity",h:"Mugler",w:"The Graham Norton Show, 2011",s:"https://www.escentual.com/blog/2011/05/19/lady-gaga-reveals-her-favourite-fragrance-and-theres-no-blood-note-in-sight/"},
{n:"Scarlett Johansson",g:"Screen",p:"Terre d'Hermès",h:"Hermès",sl:"hermes-terre-d-hermes-men",i:"216401212",w:"Who What Wear interview",s:"https://hollywoodlife.com/shop/scarlett-johanssons-signature-scent-on-sale-feminine-perfume-5259521"},
{n:"Jennifer Aniston",g:"Screen",p:"Anaïs Anaïs",h:"Cacharel",sl:"cacharel-anais-anais-l-original-women",i:"216260729",w:"E! interview, 2015 (her teen favourite)",s:"https://www.womanandhome.com/beauty/jennifer-aniston-perfume/"},
{n:"Lenny Kravitz",g:"Music",p:"Polo",h:"Ralph Lauren",sl:"ralph-lauren-polo-men",i:"216530663",w:"The Gentleman's Journal, 2025 (his first cologne)",s:"https://www.thegentlemansjournal.com/article/lenny-kravitz-interview-2025/"},
{n:"Nicole Kidman",g:"Screen",p:"Dave",h:"Henry Rose",w:"Her own Instagram Story, Met Gala 2025",s:"https://www.purewow.com/beauty/nicole-kidman-henry-rose-perfume"}
];
